name: Sbuild Debian Package
description: (Cross-)Build a debian package using sbuild
branding:
  icon: package
inputs:
  distro:
    description: Which Debian distribution to use
    required: false
    default: bullseye
  arch:
    description: Host architecture to build the package
    required: false
    default: amd64
outputs:
  deb-package:
    description: The name of the generated Debian package
    value: ${{ steps.generate-debian-package.outputs.deb-package }}
runs:
  using: composite
  steps:
    - id: generate-debian-package
      run: ${{ github.action_path }}/build.sh
      shell: bash
      env:
        INPUTS_DISTRO: ${{ inputs.distro }}
        INPUTS_ARCH: ${{ inputs.arch }}
